---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "irslackd-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
<<<<<<< HEAD
=======
  config_options:
    defaults:
      interpreter_python: auto_legacy_silent
>>>>>>> 354adca8f1329a6cf5fb2081b405ee7d7e038ca1
verifier:
  name: ansible
