---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true

  roles:
    - role: buluma.bootstrap
    - role: buluma.epel
    - role: buluma.git
    - role: buluma.ca_certificates
    - role: buluma.npm
